apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.uuid }}-prometheus
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.uuid }}-prometheus
spec:
  type: NodePort
  ports:
    - port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    app: {{ .Values.global.uuid }}-prometheus
