kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ .Values.global.uuid }}-prometheus-config
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Values.global.uuid }}-prometheus
data:
  prometheus.yml: |-
    global:
      scrape_interval: 15s      # 数据采集时间间隔
      scrape_timeout: 10s       # 数据采集超时时间
      evaluation_interval: 1m
    scrape_configs:
    - job_name: 'kubernetes-node-cadvisor' 
      kubernetes_sd_configs:         # 抓取cAdvisor数据，是获取kubelet上/metrics/cadvisor接口数据来获取容器的资源使用情况
      - role:  node
      scheme: https
      authorization:
        type: Bearer
        credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        insecure_skip_verify: true
      metric_relabel_configs:
      - source_labels: [pod]
        regex: '^(e|jos)(\d{15,}-.*)|join-.*$'  
        action: keep
      - source_labels: [namespace]
        regex: '([^\\-]+)(?:-(.+))?'
        replacement: $1
        target_label: workspace_id
        action: replace
      - source_labels: [namespace]
        regex: '([^\\-]+)(?:-(.+))?'
        replacement: $2
        target_label: project_id
        action: replace
      - source_labels: [pod]
        regex: '([^\\-]+)(?:-(.+))?'
        replacement: $1
        target_label: app_id
        action: replace
      relabel_configs:
      - action: labelmap
        regex: __meta_kubernetes_node_label_(.+)
      - target_label: __address__
        replacement: kubernetes.default.svc:443
      - source_labels: [__meta_kubernetes_node_name]
        regex: (.+)
        target_label: __metrics_path__
        replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
    - job_name: 'kubernetes-node'
      kubernetes_sd_configs:    # 使用k8s的服务发现
      - role: node              # 使用node角色，它使用默认的kubelet提供的http端口来发现集群中每个node节点。
      metrics_path: /metrics
      scheme: https
      authorization:
        type: Bearer
        credentials_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      tls_config:
        insecure_skip_verify: true
      metric_relabel_configs:
      - source_labels: [namespace]
        regex: '([^\\-]+)(?:-(.+))?'
        replacement: $1
        target_label: workspace_id
        action: replace
      - source_labels: [namespace]
        regex: '([^\\-]+)(?:-(.+))?'
        replacement: $2
        target_label: project_id
        action: replace
      - source_labels: [pod]
        regex: '([^\\-]+)(?:-(.+))?'
        replacement: $1
        target_label: app_id
        action: replace
      relabel_configs:          # 重新标记
      - source_labels: [__address__] # 配置的原始标签，匹配地址
        regex: '(.*):10250'          # 匹配带有10250端口的ip:10250
        replacement: '${1}:9100'     # 匹配到的ip:10250的ip保留替换成${1}
        target_label: __address__    # 新生成的地址
        action: replace
      - action: labelmap             # 匹配到下面正则表达式的标签会被保留
        regex: __meta_kubernetes_node_label_(.+)
    - job_name: 'kubernetes-apiserver'   # apiserver 监控
      kubernetes_sd_configs:
      - role: endpoints
      scheme: https
      tls_config:
        ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
      bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
      relabel_configs:
      - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
        action: keep
        regex: default;kubernetes;https  # 正则匹配到的默认空间下的service名字是kubernetes，协议是https的endpoint类型保留下来
    - job_name: 'kubernetes-kube-state-metrics'
      kubernetes_sd_configs:
      - role: endpoints
      metric_relabel_configs:
      - source_labels: [namespace]
        regex: '([^\\-]+)(?:-(.+))?'
        replacement: $1
        target_label: workspace_id
        action: replace
      - source_labels: [namespace]
        regex: '([^\\-]+)(?:-(.+))?'
        replacement: $2
        target_label: project_id
        action: replace
      - source_labels: [pod]
        regex: '([^\\-]+)(?:-(.+))?'
        replacement: $1
        target_label: app_id
        action: replace
      relabel_configs:
      - source_labels: [__meta_kubernetes_service_label_k8s_app]
        action: keep
        regex: {{ .Values.global.uuid }}-kube-state-metrics
      - source_labels: [__address__]
        target_label: __address__
      - source_labels: [__meta_kubernetes_namespace]
        target_label: kubernetes_namespace
      - source_labels: [__meta_kubernetes_service_name]
        target_label: kubernetes_service_name
