apiVersion: v1
kind: Service
metadata:
  labels:
    kubernetes.io/cluster-service: 'true'
    kubernetes.io/name: monitoring-grafana
  name: {{ .Values.global.uuid }}-monitoring-grafana
  namespace: {{ .Values.global.namespace }}
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    k8s-app: {{ .Values.global.uuid }}-grafana
  type: ClusterIP