kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.global.uuid }}-grafana
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 10240m
spec:
  ingressClassName: {{ .Values.initJos.uuid }}-nginx
{{- if eq .Values.initJos.network "https" }}
  tls:
    - hosts:
        - {{ .Values.domain.grafana }}
      secretName: {{ .Values.global.uuid }}-grafana
{{- end }}
  rules:
    - host: {{ .Values.domain.grafana }}
      http:
        paths:
          - path: /
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .Values.global.uuid }}-monitoring-grafana
                port:
                  number: 3000