{{- if eq .Values.initJos.network "https" }}
kind: Secret
apiVersion: v1
metadata:
  name: {{ .Values.global.uuid }}-grafana
  namespace: {{ .Values.global.namespace }}
data:
  tls.crt: >-
    {{ .Values.tls.crt }}
  tls.key: >-
    {{ .Values.tls.key }}
type: kubernetes.io/tls
{{- end }}