apiVersion: v1
kind: Service
metadata:
#修改 namespace 
  labels:
    app: {{ .Values.global.uuid }}-mysql-svc
  name: {{ .Values.global.uuid }}-mysql-svc
  namespace: {{ .Values.global.namespace }}
spec:
#prot 根据环境配置
  ports:
    - port: 3306
      protocol: TCP
      targetPort: 3306
      nodePort: 31469
  selector:
    app: {{ .Values.global.uuid }}-mysql
  type: NodePort
