apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.uuid }}-mysql
  namespace: {{ .Values.global.namespace }}
data:
  my.cnf: |-
    [mysqld]
    max_connections=2000
    table_open_cache=2000
    mysqlx_max_connections=2000
