apiVersion: v1
kind: Service
metadata:
  annotations:
    prometheus.io/scrape: 'true'
  name: {{ .Values.global.uuid }}-kube-state-metrics
  namespace: {{ .Values.global.namespace }}
  labels:
    k8s_app: {{ .Values.global.uuid }}-kube-state-metrics
spec:
  type: ClusterIP
  ports:
  - name: http-main
    port: 8080
    protocol: TCP
  - name: http-self
    port: 8081
    protocol: TCP
  selector:
    app: {{ .Values.global.uuid }}-kube-state-metrics