apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.global.uuid }}-gitlab
  namespace: {{ .Values.global.namespace }}
spec:
  selector:
    matchLabels:
      name: {{ .Values.global.uuid }}-gitlab
  template:
    metadata:
      labels:
        name: {{ .Values.global.uuid }}-gitlab

    spec:
      initContainers:
        - name: fix-permissions
          image: {{ .Values.harbor.host }}{{ .Values.image.busybox }}
          command: [ "sh", "-c", "chown -R 1000:1000 /home/git/data" ]
          securityContext:
            privileged: true
          volumeMounts:
            - name: data
              mountPath: /home/git/data
              subPath: data/gitlab/data
      containers:
        - name: gitlab
          image: {{ .Values.harbor.host }}{{ .Values.image.gitlab }}
          imagePullPolicy: IfNotPresent
          env:
            - name: TZ
              value: Asia/Shanghai
            - name: GITLAB_TIMEZONE
              value: Beijing
            - name: GITLAB_SECRETS_DB_KEY_BASE
              value: long-and-random-alpha-numeric-string
            - name: GITLAB_SECRETS_SECRET_KEY_BASE
              value: long-and-random-alpha-numeric-string
            - name: GITLAB_SECRETS_OTP_KEY_BASE
              value: long-and-random-alpha-numeric-string
            - name: GITLAB_ROOT_PASSWORD
              value: Admin@123
            - name: GITLAB_ROOT_EMAIL
              value: 657407048@qq.com
            - name: GITLAB_HOST
              value: {{ .Values.domain.gitlab_app }}.{{ .Values.initJos.hosts }}
            - name: GITLAB_PORT
              value: "{{ .Values.initJos.nodePort }}"
            - name: GITLAB_SSH_PORT
              value: "30022"
            - name: GITLAB_NOTIFY_ON_BROKEN_BUILDS
              value: "true"
            - name: GITLAB_NOTIFY_PUSHER
              value: "false"
            - name: GITLAB_BACKUP_SCHEDULE
              value: daily
            - name: GITLAB_BACKUP_TIME
              value: 01:00
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: {{ .Values.global.uuid }}-postgresql.{{ .Values.global.namespace }}.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: gitlab
            - name: DB_PASS
              value: passw0rd
            - name: DB_NAME
              value: gitlab_production
            - name: REDIS_HOST
              value: {{ .Values.global.uuid }}-redis.{{ .Values.global.namespace }}.svc.cluster.local
            - name: REDIS_PORT
              value: "6379"
          ports:
            - name: http
              containerPort: 80
            - name: ssh
              containerPort: 22
          resources:
            limits:
              cpu: '1'
              memory: 3Gi
            requests:
              cpu: 100m
              memory: 2Gi
          volumeMounts:
            - name: host-time
              mountPath: /etc/localtime
              readOnly: true
            - mountPath: /home/git/data
              name: data
              subPath: data/gitlab/data
            - mountPath: /etc/gitlab
              name: data
              subPath: data/gitlab/config
            - mountPath: /var/log/gitlab
              name: data
              subPath: data/gitlab/log
            - mountPath: /var/opt/gitlab
              name: data
              subPath: data/gitlab/opt
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 180
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            timeoutSeconds: 5
      volumes:
        - hostPath:
            path: /etc/localtime
            type: ''
          name: host-time
        - name: data
          persistentVolumeClaim:
            claimName: {{ .Values.global.uuid }}-standalone-pvc