# License: Apache-2.0

---

- name: install authconfig
  dnf:
    name: authconfig
    state: present
  become: yes

- name: disable fingerprint to avoid ssh timeout issues
  command: authconfig --disablefingerprint --update
  changed_when: false
  become: yes
