# License: Apache-2.0

---

- debug:
    msg: "Setting up OS"

#- include_tasks: disable_fingerprint.yml
- include_tasks: disable_swap.yml
- include_tasks: disable_selinux.yml
- include_tasks: build_noproxy.yml
- include_tasks: proxy_os_env_remove.yml
- include_tasks: proxy_os_env_add.yml
- include_tasks: reset_connection.yml
- include_tasks: enable_ipv4_forwarding.yml
- include_tasks: install_tools.yml
# - include_tasks: install_china_repository.yml
# - include_tasks: install_required_package.yml
