# License: Apache-2.0
---
- name: Remove proxy from /etc/environment
  lineinfile:
    dest: /etc/environment
    regexp: "^{{ item }}=.*"
    state: absent
  with_items:
    - http_proxy
    - https_proxy
    - HTTPS_PROXY
    - HTTP_PROXY
    - FTP_PROXY
    - ftp_proxy
    - no_proxy
    - NO_PROXY
  when: proxy_remove_old
  become: yes
