# License: Apache-2.0

---

- name: check if kubeadm is installed
  shell: command -v kubeadm >/dev/null 2>&1
  register: kubeadm_exec
  ignore_errors: yes
  changed_when: false

- name: reset kubeadm
  command: kubeadm reset --force
  when: kubeadm_exec.rc == 0
  become: yes

- name: remove kubeconfig
  file:
    path: /root/.kube/
    state: absent

- name: remove kubernetes artifacts
  file:
    path: /etc/kubernetes
    state: absent
  ignore_errors: yes
