apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.uuid }}-gitlab
  namespace: {{ .Values.global.namespace }}
  labels:
    name: {{ .Values.global.uuid }}-gitlab
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
    - name: ssh
      port: 22
      targetPort: 22
  type: ClusterIP
  selector:
    name: {{ .Values.global.uuid }}-gitlab